include:
  - ./services/immich-app/docker-compose.yaml
  - ./services/home-assistant/docker-compose.yaml
  - ./services/copyparty/docker-compose.yaml
  - ./services/mc-server/docker-compose.yaml
  - ./services/calibre-web/docker-compose.yaml
services: {}
