services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: "if_not_present"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "Europe/Warsaw"
      TYPE: "VANILLA"
      VERSION: "1.21.11"
      MODE: "survival"
      DIFFICULTY: "hard"
      SPAWN_PROTECTION: "0"
    restart: unless-stopped
    volumes:
      - ./data:/data
